Identity profile is read form a file and sent as http request headers.
aselalee/silver pull request #1
Opened 2018-12-21 05:49 UTC by aselalee

If the file is not present, a new file is created with a randomly
generated id number. This behavior can be turned on by passing "i" as a
command line argument.
Profile information file will contain a set of key/value pairs.
Each key/value pair will be read and added to the request header.
Can add any number of key/value pairs.
Key "identity" is used to store the customer id.
Key "timezone" is not stored in the file but added to the header.
Ex:
identity=192837465
channel=stable

2018-12-24 05:33 UTC, hiroxy requested changes

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +    const profileFileName string = "identity.profile"
{exename}-identity.conf ?

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +	sendIdProfile   = flag.Bool("i", false, "Send identity profile when checking for new version.")
Add the text "... new versions.  This allows the server to deliver a custom update, such as a canary version targeted at just this install.

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +    const profileFileName string = "identity.profile"
{exename}-profile.conf ?

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +    "bufio"
Using tab instead of 4 spaces is Go custom.
In addition, always should apply `goimports` or `gofmt`, I recommend the former, automatically when you save your code. The tool handles these kinds of things.

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +           len(strings.Trim(keyVal[0], " \r\n\t")) > 0 &&
Using `strings.TrimSpace()` would be better.

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +        }
Would be better handling an error case.

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +    // Add timezone. Gives a broad geo location.
Why is the timezone added to the header here? It seems the timezone doesn't relate the ID.

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +func addIdProfileToRequestHeader(req *http.Request) {
would be better to return `error` to the caller?

2018-12-24 05:33 UTC, hiroxy commented on updater/updater.go
> +            req.Header.Set(customHeader+keyVal[0], keyVal[1])
If I implemented this, I would have created:
* A struct that holds values to set custom headers
* Methods that generate each value of the custom header and append custom headers to an HTTP request.

2019-05-20 06:07 UTC, aselalee commented
More proposed changes. Closing review. Will create a new one once done.

2019-05-20 06:07 UTC, closed without merging